global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "nim-llm"
    metrics_path: /v1/metrics
    static_configs:
      - targets:
          - "192.168.5.173:8000"
        labels:
          app: "nim-llm"
